backend/models/Transaksi.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "transaksi".
 *
 * @property integer $id_transaksi
 * @property integer $id_staff
 * @property integer $id_pelanggan
 * @property string $kode_transaksi
 * @property string $tanggal_check_in
 * @property string $tanggal_check_out
 * @property integer $durasi
 * @property integer $jumlah_kamar
 * @property integer $jumlah_pengunjung
 * @property string $status
 * @property double $total_pembayaran
 * @property double $sisa_pembayaran
 *
 * @property Pembayaran[] $pembayarans
 */
class Transaksi extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'transaksi';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['durasi', 'jumlah_kamar', 'jumlah_pengunjung'], 'integer'],
            [['id_pelanggan', 'kode_transaksi', 'durasi', 'jumlah_kamar', 'jumlah_pengunjung'], 'required'],
            [['tanggal_check_in', 'tanggal_check_out'], 'safe'],
            [['total_pembayaran', 'sisa_pembayaran'], 'number'],
            [['kode_transaksi'], 'string', 'max' => 64],
            [['status'], 'string', 'max' => 60],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_transaksi' => 'Id Transaksi',
            'kode_transaksi' => 'Kode Transaksi',
            'tanggal_check_in' => 'Tanggal Check In',
            'tanggal_check_out' => 'Tanggal Check Out',
            'durasi' => 'Durasi',
            'jumlah_kamar' => 'Jumlah Kamar',
            'jumlah_pengunjung' => 'Jumlah Pengunjung',
            'status' => 'Status',
            'total_pembayaran' => 'Total Pembayaran',
            'sisa_pembayaran' => 'Sisa Pembayaran',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPembayarans()
    {
        return $this->hasMany(Pembayaran::className(), ['id_transaksi' => 'id_transaksi']);
    }
}

backend/controllers/TransaksiController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Transaksi;
use backend\models\TransaksiSearch;
use kartik\date\DatePicker;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\SqlDataProvider;
use yii\data\ActiveDataProvider;
use backend\models\Pembayaran;
use yii\web\ForbiddenHttpException;

/**
 * TransaksiController implements the CRUD actions for Transaksi model.
 */
class TransaksiController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Transaksi models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new Transaksi();
        $count = (new \yii\db\Query())
        ->from('transaksi')
        ->innerJoin('pembayaran', 'transaksi.id_transaksi = pembayaran.id_transaksi')
        ->count(); 

        $dataProvider = new SqlDataProvider([
            'sql' => 'SELECT t.id_transaksi FROM transaksi t INNER JOIN pembayaran p on t.id_transaksi = p.id_transaksi 
            INNER JOIN pelanggan c on t.id_pelanggan = c.id_pelanggan ORDER BY t.id_transaksi DESC',
            'pagination' => [
                'pageSize' => 20,
                'totalCount'  => $count,
            ],
            'sort' => [
                'attributes' => [
                    'id_pembayaran',
                ],
            ],
        ]);


        // print_r($dataProvider->getModels());
        // die(); 

        $sql = "SELECT * FROM transaksi WHERE DATEDIFF(CURDATE(),transaksi.tanggal_booking) > 4 AND transaksi.status = 'menunggu pembayaran'";
        $rawData = Yii::$app->db->createCommand($sql)->queryAll();

        foreach ($rawData as $transaksi) {
                $sqlDetail = "SELECT * FROM detail_transaksi WHERE id_transaksi = ".$transaksi['id_transaksi'];
                $rawDataDetail = Yii::$app->db->createCommand($sqlDetail)->queryAll();
                foreach ($rawDataDetail as $key => $detailTransaksi) {  
                    $connectionDetail = \Yii::$app->db;
                    $commandDetail = $connectionDetail->createCommand("DELETE FROM transaksi WHERE id_transaksi=".$transaksi['id_transaksi']);
                    $commandDetail->execute();                                      
                } 
                $connectionTransaksi = \Yii::$app->db;
                $commandTransaksi = $connectionTransaksi->createCommand("DELETE FROM transaksi WHERE id_transaksi=".$transaksi['id_transaksi']);
                $commandTransaksi->execute(); 
            }          

        $models = $dataProvider->getModels();

        return $this->render('index', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSearch()
    {
        $model = new Transaksi();


        if ($model->load(Yii::$app->request->post())) {
            $dataProvider = new SqlDataProvider([
            'sql' => "SELECT * FROM transaksi t INNER JOIN pembayaran p on t.id_transaksi = p.id_transaksi INNER JOIN pelanggan c on t.id_pelanggan = c.id_pelanggan WHERE t.kode_transaksi = 'SIHSNfc73483cfe'",
                'pagination' => [
                    'pageSize' => 10,
                ],
                'sort' => [
                    'attributes' => [
                        'id_pembayaran',
                    ],
                ],
            ]);          

            return $this->render('index', [
                'model' => $model,
                'dataProvider' => $dataProvider,
            ]);
        }else{
            $this->actionIndex();           
        }
    }
    /**
     * Displays a single Transaksi model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $pembayaran = Pembayaran::find()->where(['id_transaksi' => $id]);
        $dataProvider = new ActiveDataProvider(
            [
                'query'=>$pembayaran,
                'pagination'=>[
                    'pageSize'=>10
                ]
            ]
        );

        $dataProvider1 = new SqlDataProvider([
            'sql' => "SELECT * from kamar k INNER JOIN jenis_kamar j ON k.id_jenis_kamar = j.id
                      INNER JOIN detail_transaksi d on d.id_kamar = k.id_kamar where d.id_transaksi = $id",
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'attributes' => [
                    'no_kamar',
                ],
            ],
        ]);

        $query =  new \yii\db\Query;
        $query->select(['*'])  
        ->from('pembayaran')
        ->where(['id_transaksi' => $id]);

        $command = $query->createCommand();
        $pembayaran = $command->queryOne();      

        return $this->render('view', [
            'model' => $this->findModel($id),
            'dataProvider'=>$dataProvider,
            'dataProvider1' => $dataProvider1,
            'pembayaran' => $pembayaran,
        ]);
    }

    /**
     * Creates a new Transaksi model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Transaksi();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_transaksi]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionEmail($id_transaksi)
    {
        if(Yii::$app->user->can('kirim-tiket')){
            $date = date('H:i');
            echo $date;
            $sapa = '';
            if ($date < 12)
                $sapa = "Pagi";
            else if ($date < 14)
                $sapa = 'Siang';
            else if ($date < 18)
                $sapa = 'Sore';

            $query =  new \yii\db\Query;
            $query->select(['*'])  
            ->from('pelanggan')
            ->innerJoin('transaksi', 'pelanggan.id_pelanggan = transaksi.id_pelanggan')
            ->where(['transaksi.id_transaksi' => $id_transaksi]);

            $command = $query->createCommand();
            $model = $command->queryOne();        

            $message = 'Pemberitahuan Pembayaran Berhasil<br>'
                    . 'Selamat ' . $sapa .' '.$model['nama']. '<br>'
                    .' Kami dari Hotel Sere Nauli hendak memberitahukan bahwa pembayaran yang anda lakukan berhasil'
                    . ' <br> <br>Atas perhatian Bapak/Ibu Sekalian, Kami Ucapkan Terimakasih'
                    . '<br><br><br> <hr> Dikirim oleh : <br>'
                    . '<b>Sistem Informasi Hotel Sere Nauli<b>';

            $tujuan = $model['email'];    
            
            $path = "C:\Users\Okta\Downloads\SIHSN$id_transaksi.pdf";

            $email = Yii::$app->mailer->compose()
                    ->setFrom([\Yii::$app->params['supportEmail'] => 'SIHSN'])
                    ->setTo($tujuan)
                    ->setSubject("Notifikasi Pembayaran diterima")
                    ->setHtmlBody($message)
                    ->attach($path)
                    ->send();

            $connection = \Yii::$app->db;
            $command = $connection->createCommand("UPDATE transaksi SET status_struk='sudah dikirim' WHERE id_transaksi=$id_transaksi");
            $command->execute();                
            return $this->redirect(['index']);
        }else{
            throw new ForbiddenHttpException;
        }
    }

    /**
     * Updates an existing Transaksi model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_transaksi]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Transaksi model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionCheckin($id)
    {
        if(Yii::$app->user->can('check-in')){
            $connection = \Yii::$app->db;
            $command = $connection->createCommand("UPDATE transaksi SET status='check in' WHERE id_transaksi=$id");
            $command->execute();                 
            return $this->redirect(['index']);
        }else{
            throw new ForbiddenHttpException;
        }
    }    

    public function actionCheckout($id)
    {
        if(Yii::$app->user->can('check-out')){
            $connection = \Yii::$app->db;        
            $command = $connection->createCommand("UPDATE transaksi SET status='check out' WHERE id_transaksi=$id");
            $command->execute();           
            return $this->redirect(['index']);
        }else{
            throw new ForbiddenHttpException;
        }
    }  

    public function actionChart()
    {
        if(Yii::$app->user->can ('melihat-laporan'))
        {
            $model = new Transaksi();
            if($model->load(Yii::$app->request->post()))
            {
                $sql = "SELECT  *,SUM(t.durasi) as banyak_bookingan FROM transaksi t 
                        INNER JOIN detail_transaksi d on t.id_transaksi = d.id_transaksi
                        INNER JOIN kamar k on k.id_kamar = d.id_kamar 

frontend/controllers/TransaksiController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Transaksi;
use frontend\models\TransaksiSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use common\models\Pelanggan;

/**
 * TransaksiController implements the CRUD actions for Transaksi model.
 */
class TransaksiController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Transaksi models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TransaksiSearch();      
        $user_id = Yii::$app->user->id;
        $pelanggan = Pelanggan::findOne(['account_id' => $user_id]);
        $query = Transaksi::find()->where(['id_pelanggan' => $pelanggan['id_pelanggan']]);        
        $provider = new ActiveDataProvider([
            'query' => $query,
            'sort' => [
                'defaultOrder' => [
                    'id_transaksi' => SORT_DESC
                ]
            ],            
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);  

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $provider,
            'pelanggan' => $pelanggan['id_pelanggan'],
        ]);
    }

    /**
     * Displays a single Transaksi model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Transaksi model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Transaksi();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_transaksi]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Transaksi model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_transaksi]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Transaksi model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Transaksi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Transaksi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Transaksi::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/transaksi/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;
use yii\helpers\ArrayHelper;
use backend\models\JenisKamar;

/* @var $this yii\web\View */
/* @var $model backend\models\Transaksi */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="transaksi-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'tanggal_check_in')->widget(
    DatePicker::className(), [
        // inline too, not bad
         'inline' => false,
         // modify template for custom rendering
        //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
        'clientOptions' => [
            'autoclose' => true,
            'format' => 'yyyy-mm-dd'
        ]
]);?> 

    <?= $form->field($model, 'tanggal_check_out')->widget(
    DatePicker::className(), [
        // inline too, not bad
         'inline' => false,
         // modify template for custom rendering
        //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
        'clientOptions' => [
            'autoclose' => true,
            'format' => 'yyyy-mm-dd'
        ]
]);?> 

    <?= $form->field($model, 'jumlah_kamar')->textInput() ?>

    


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/transaksi/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\widgets\Pjax;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use frontend\models\Transaksi;

/* @var $this yii\web\View */
/* @var $model backend\models\TransaksiSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="transaksi-search">
    <?php Pjax::begin();?>
    <?php $form = ActiveForm::begin([
        'action'=>Url::to(['transaksi/search']),
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'kode_transaksi')
        ->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Transaksi::find()
        ->where(['status' => 0])
        ->all(), 'kode_transaksi', 'kode_transaksi'),
            'language' => 'en',
            'options' => ['placeholder' => 'Kode Booking'],
            'pluginOptions' => [
                'allowClear' => true
                ],
            ])->label('Kode Booking');
    ?>

    <?php // echo $form->field($model, 'id_staff') ?>

    <?php // echo $form->field($model, 'id_pelanggan') ?>

    <?php // echo $form->field($model, 'tanggal_check_in') ?>

    <?php // echo $form->field($model, 'tanggal_check_out') ?>

    <?php // echo $form->field($model, 'durasi') ?>

    <?php // echo $form->field($model, 'jumlah_kamar') ?>

    <?php // echo $form->field($model, 'jumlah_pengunjung') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'total_pembayaran') ?>

    <?php // echo $form->field($model, 'sisa_pembayaran') ?>

    <div class="form-group">
        <?= Html::submitButton('Cari', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    <?php Pjax::end();?>

</div>

backend/views/transaksi/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Transaksi */

$this->title = 'Create Transaksi';
$this->params['breadcrumbs'][] = ['label' => 'Transaksis', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="transaksi-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/transaksi/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\LinkPager;
use kartik\select2\Select2;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\TransaksiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Transaksi';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="transaksi-index">

    
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <h3> No rekening Pembayaran : <font color= #DE8220 >113140057293 </font>(BNI)</h3>
    <p>
<br>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [

            //'id_transaksi',
            //'id_staff',
            //'id_pelanggan',
            'tanggal_check_in',
            'tanggal_check_out',
            // 'durasi',
             'jumlah_kamar',
            // 'jumlah_pengunjung',
            // 'status',
             'total_pembayaran',
            // 'sisa_pembayaran',
            [
                'attribute' => 'Aksi',
                'format' => 'raw',
                'value' => function ($model) {
                    if($model->total_pembayaran == $model->sisa_pembayaran)
                    {
                        return '<div>'. Html::a('Bayar', [
                        'pembayaran/create','id'=>$model->id_transaksi],
                        ['class' => 'btn btn-info']).'</div>';
                    }
                    else
                    {
                        return "<div><h4><span class='label label-info'>telah dikonfirmasi</span></h4></div>";
                    }
                },
            ],

            
        ],
    ]); ?>
</div>

backend/views/transaksi/search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\widgets\Pjax;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use frontend\models\Transaksi;

/* @var $this yii\web\View */
/* @var $model backend\models\Transaksi */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="transaksi-form">

    <?php $form = ActiveForm::begin([
        'action'=>Url::to(['transaksi/search']),
    ]); ?>

    <?= $form->field($model, 'kode_transaksi')
        ->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Transaksi::find()
        ->where(['status' => 0])
        ->all(), 'kode_transaksi', 'kode_transaksi'),
            'language' => 'en',
            'options' => ['placeholder' => 'Kode Booking'],
            'pluginOptions' => [
                'allowClear' => true
                ],
            ])->label('Kode Booking');
    ?>

    <div class="form-group">
        <?= Html::submitButton('Cari', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/transaksi/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Transaksi */

$this->title = 'Update Transaksi: ' . $model->id_transaksi;
$this->params['breadcrumbs'][] = ['label' => 'Transaksis', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_transaksi, 'url' => ['view', 'id' => $model->id_transaksi]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="transaksi-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/transaksi/view.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Transaksi */

$this->title = 'Update Transaksi: ' . $model->id_transaksi;
$this->params['breadcrumbs'][] = ['label' => 'Transaksis', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_transaksi, 'url' => ['view', 'id' => $model->id_transaksi]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="transaksi-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>